import type { ApexConfig } from './ConfigSchema';

export const DEFAULT_CONFIG: ApexConfig = {
  'apex.chat.fontSize': 14,
  'apex.chat.theme': 'dark',
  'apex.chat.showLineNumbers': true,
  'apex.chat.autoScroll': true,
  'apex.chat.enterToSend': true,
  'apex.modes.default': 'plan',
  'apex.modes.autoSwitch': false,
  'apex.modes.showConfirmation': true,
  'apex.modes.custom': [],
  'apex.modes.rememberLast': true,
  'apex.provider': 'openai',
  'apex.providers.openai': {
    apiKey: '',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o',
    maxTokens: 4096,
    temperature: 0.7,
    topP: 1,
    contextWindow: 128000,
  },
  'apex.providers.anthropic': {
    apiKey: '',
    baseUrl: 'https://api.anthropic.com/v1',
    model: 'claude-3-5-sonnet-20241022',
    maxTokens: 4096,
    temperature: 0.7,
    topP: 1,
    contextWindow: 200000,
  },
  'apex.providers.ollama': {
    baseUrl: 'http://localhost:11434',
    model: 'llama3',
    maxTokens: 4096,
    temperature: 0.7,
    contextWindow: 8192,
  },
  'apex.providers.azure-openai': {
    apiKey: '',
    baseUrl: '',
    model: 'gpt-4o',
    maxTokens: 4096,
    temperature: 0.7,
    topP: 1,
    contextWindow: 128000,
    deploymentName: '',
    apiVersion: '2024-10-01-preview',
  },
  'apex.providers.google-gemini': {
    apiKey: '',
    baseUrl: '',
    model: 'gemini-1.5-pro',
    maxTokens: 8192,
    temperature: 0.7,
    contextWindow: 1048576,
  },
  'apex.providers.github-copilot': {
    apiKey: '',
    model: 'gpt-4o-copilot',
    maxTokens: 4096,
    contextWindow: 128000,
  },
  'apex.providers.openrouter': {
    apiKey: '',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'openai/gpt-4o',
    maxTokens: 4096,
    temperature: 0.7,
    topP: 1,
    contextWindow: 128000,
  },
  'apex.providers.nvidia-nim': {
    apiKey: '',
    baseUrl: 'https://nim.ngc.nvidia.com',
    model: 'nvidia/llama-3.1-nemotron-70b-instruct',
    maxTokens: 4096,
    temperature: 0.7,
    topP: 1,
    contextWindow: 128000,
  },
  'apex.providers.opencode-zen': {
    apiKey: '',
    baseUrl: 'https://api.opencode.ai/v1',
    model: 'zen-1.0',
    maxTokens: 4096,
    contextWindow: 128000,
  },
  'apex.providers.puter-ai': {
    apiKey: '',
    baseUrl: 'https://api.puter.com/v1',
    model: 'puter-gpt-4o',
    maxTokens: 4096,
    contextWindow: 128000,
  },
  'apex.agentic.enabled': true,
  'apex.agentic.maxRequests': 25,
  'apex.agentic.timeout': 300,
  'apex.agentic.shellPath': '',
  'apex.agentic.tools.fileRead': 'allow',
  'apex.agentic.tools.fileWrite': 'ask',
  'apex.agentic.tools.fileEdit': 'ask',
  'apex.agentic.tools.fileSearch': 'allow',
  'apex.agentic.tools.terminalExec': 'ask',
  'apex.agentic.tools.codeSearch': 'allow',
  'apex.agentic.tools.webSearch': 'ask',
  'apex.agentic.tools.webFetch': 'ask',
  'apex.agentic.tools.globSearch': 'allow',
  'apex.learning.enabled': true,
  'apex.learning.autoDetectPatterns': true,
  'apex.learning.learnFromEdits': true,
  'apex.learning.maxStoredRules': 1000,
  'apex.learning.confidenceThreshold': 0.7,
  'apex.learning.exportPath': '',
  'apex.subAgents.maxConcurrent': 3,
  'apex.subAgents.defaultModel': '',
  'apex.subAgents.timeout': 120,
  'apex.skills.autoInstall': true,
  'apex.skills.autoImprove': true,
  'apex.skills.maxActive': 5,
  'apex.skills.github.enabled': true,
  'apex.skills.github.registryUrl': 'apex-skills/registry',
  'apex.skills.github.autoDiscover': true,
  'apex.skills.github.searchTopics': ['apex-skill', 'claude-command', 'codex-agent', 'cursor-rule'],
  'apex.skills.github.token': '',
  'apex.skills.marketplaceUrl': '',
  'apex.skills.improvementMode': 'diff-review',
  'apex.skills.localPath': '',
  'apex.skills.sources.codex': true,
  'apex.skills.sources.claude': true,
  'apex.skills.sources.zcode': true,
  'apex.skills.sources.codexPath': '',
  'apex.skills.sources.claudePath': '',
  'apex.skills.sources.zcodePath': '',
  'apex.skills.sourceMode': 'both',
  'apex.advanced.customInstructions': '',
  'apex.advanced.autoSummarize': true,
  'apex.advanced.language': 'en',
  'apex.advanced.sounds': false,
  'apex.advanced.debugMode': false,
};
